### ISSUE TITLE
Thai language word segmentation

### ISSUE THREAD

**Issue by pepa65** [go-ego/ego#4]
Hi! I was wondering what it would take to support Thai language word segmentation, for instance based on https://github.com/tlwg/swath

**Comment by vcaesar** [comment]
Please move it to riot, here is the web framework, I do not know whether Thai is as `spacing ` as English.

**Comment by pepa65** [comment]
I noticed there was one for Chinese, that is whyvI asked.

**Comment by vcaesar** [comment]
Riot will be v0.20.0 support.
